language: node_js
node_js:
  - "10"

script:
- npm run lint

deploy:
  provider: script
  script: bash scripts/minify.sh
  github-token: $GITHUB_TOKEN
  on:
    branch: master

addons:
  apt:
    packages:
    - grunt-cli
